webapp/news/models.py
from webapp.db import db
from datetime import datetime
from sqlalchemy.orm import relationship


class News(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    url = db.Column(db.String, nullable=False, unique=True)
    published = db.Column(db.DateTime, nullable=False)
    text = db.Column(db.Text, nullable=True)

    def comments_count(self):
        return Comment.query.filter(Comment.news_id == self.id).count()

    def __repr__(self):
        return '<News {} {}>'.format(self.title, self.url)


class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.String, nullable=False)
    created = db.Column(db.DateTime, nullable=False, default=datetime.now())

    news_id = db.Column(
        db.Integer,
        db.ForeignKey('news.id', ondelete='CASCADE'),
        index=True
    )
    user_id = db.Column(
        db.Integer,
        db.ForeignKey('user.id', ondelete='CASCADE'),
        index=True
    )

    news = relationship('News', backref='comments')
    user = relationship('User', backref='comments')

    def __repr__(self):
        return '<Comment {}>'.format(self.id)

webapp/user/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from webapp.db import db


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(
        db.String(50),
        nullable=False,
        index=True,
        unique=True)
    password = db.Column(db.String(128), nullable=False)
    role = db.Column(db.String(10), nullable=False, index=True)
    email = db.Column(db.String(50), unique=True)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    @property
    def is_admin(self):
        return self.role == 'admin'

    def __repr__(self):
        return '<User {}>'.format(self.username)

webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError

from webapp.user.models import User

class LoginForm(FlaskForm):
    username = StringField(
        "User Name",
        validators=[DataRequired()],
        render_kw={"class": "form-control"})
    password = PasswordField(
        "Password",
        validators=[DataRequired()],
        render_kw={"class": "form-control"})
    submit = SubmitField(
        "Login",
        render_kw={"class": "btn btn-primary"})
    remember_me = BooleanField(
        "Remember me",
        default=False,
        render_kw={"class": "form-check-input"})


class RegistrationForm(FlaskForm):
    username = StringField(
        "User Name",
        validators=[DataRequired()],
        render_kw={"class": "form-control"})
    email = StringField(
        "Email",
        validators=[DataRequired(), Email()],
        render_kw={"class": "form-control"})
    password = PasswordField(
        "Password",
        validators=[DataRequired()],
        render_kw={"class": "form-control"})
    password2 = PasswordField(
        "Repeat Password",
        validators=[DataRequired(), EqualTo('password')],
        render_kw={"class": "form-control"})
    submit = SubmitField(
        "Register",
        render_kw={"class": "btn btn-primary"})

    def validate_username(self, username):
        user_count = User.query.filter_by(username=username.data).count()
        if user_count > 0:
            raise ValidationError("User with this name is already exists")

    def validate_email(self, email):
        user_count = User.query.filter_by(email=email.data).count()
        if user_count > 0:
            raise ValidationError("User with this email is already exists")

webapp/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_migrate import Migrate

from webapp.db import db
from webapp.user.models import User
from webapp.user.views import blueprint as user_blueprint
from webapp.admin.views import blueprint as admin_blueprint
from webapp.news.views import blueprint as news_blueprint


def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('config.py')
    db.init_app(app)
    migrate = Migrate(app, db)

    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'user.login'
    app.register_blueprint(user_blueprint)
    app.register_blueprint(admin_blueprint)
    app.register_blueprint(news_blueprint)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)

    return app

webapp/admin/views.py
from flask import Blueprint, render_template

from webapp.user.decorators import admin_required

blueprint = Blueprint('admin', __name__, url_prefix='/admin')


@blueprint.route('/')
@admin_required
def admin_index():
    title = "Admin panel"
    return render_template('admin/index.html', page_title=title)

webapp/news/views.py
from flask import abort, Blueprint, current_app, render_template
from webapp.weather import weather_by_city
from webapp.news.models import News

blueprint = Blueprint('news', __name__)


@blueprint.route('/')
def index():
    page_title = "Python news"
    weather = weather_by_city(current_app.config['WEATHER_DEFAULT_CITY'])
    news_list = News.query.filter(News.text.isnot(None)).order_by(News.published.desc()).all()

    return render_template(
        'news/index.html',
        page_title=page_title,
        weather=weather,
        news_list=news_list)


@blueprint.route('/news/<int:news_id>')
def single_news(news_id):
    my_news = News.query.filter(News.id == news_id).first()

    if not my_news:
        abort(404)

    return render_template('news/single_news.html', page_title=my_news.title, news=my_news)

webapp/user/views.py
from flask_login import login_user, logout_user, current_user
from flask import Blueprint, render_template, flash, redirect, url_for

from webapp.db import db
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User

blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('news.index'))
    title = "Authorization"
    login_form = LoginForm()

    return render_template(
        'user/login.html',
        page_title=title,
        form=login_form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash("You've logged in successfully")

            return redirect(url_for('news.index'))

    flash("Incorrect login or password")

    return redirect(url_for('user.login'))


@blueprint.route('/logout')
def logout():
    logout_user()
    flash("You have been successfully loged out")
    return redirect(url_for('news.index'))


@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('news.index'))
    title = "Registration"
    form = RegistrationForm()
    return render_template('user/registration.html', page_title=title, form=form)


@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        news_user = User(
            username=form.username.data,
            email=form.email.data,
            role='user')
        news_user.set_password(form.password.data)
        db.session.add(news_user)
        db.session.commit()
        flash("You have been successfully registered")

        return redirect(url_for('user.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Error in field "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error)
                )
        return redirect(url_for('user.register'))

webapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/styles/atom-one-dark.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <title>
        {{ page_title }}
    </title>
  </head>
  <body>
    {% include "menu.html" %}

    <div class="container">
      
      <h1>
        {{ page_title }}
      </h1>
      {% block content %} {% endblock %}

    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>
        {{ page_title }}
    </title>
  </head>
  <body>
    <div class="container">
      
      <h1>
        {{ page_title }}
      </h1>
      
      <div class="row">
        <div class="col-8">
          {% with messages = get_flashed_messages() %}
              {% if messages %}
              <div class="alert alert-warning" role="alert">
                  {% for message in messages %}
                      {{ message }}<br>
                  {% endfor %}
              </div>
              {% endif %}
          {% endwith %}
          {% for news in news_list %}
            <h3><a href={{ news.url }}>{{ news.title }}</a></h3>
            <p>{{ news.published.strftime('%d.%m.%Y') }}</p>
            <hr />
          {% endfor %}
        </div>
        <div class="col-4">
          <h2>
            Weather forecast
          </h2>
          {% if weather %}
            Now {{ weather.temp_C }}, feels like {{ weather.FeelsLikeC }}
          {% else %}
            Service is unavailable now
          {% endif %}
        </div>

      </div>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Python News</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home</a>
        </li>

      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      <ul class="navbar-nav" >
        {% if current_user.is_authenticated %}
          <li class="nav-item">
            <span class="nav-link">Hello, {{ current_user.username }}</span>
          </li>
          {% if current_user.is_admin %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('admin.admin_index') }}">Admin</a>
            </li>           
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.logout') }}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.login') }}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.register') }}">Registration</a>
          </li>          
          {% endif %}
        
      </ul>
    </div>
  </nav>

webapp/templates/news/index.html
{% extends "base.html" %}
{% block content %}     
      <div class="row">
        <div class="col-8">
          {% with messages = get_flashed_messages() %}
              {% if messages %}
              <div class="alert alert-warning" role="alert">
                  {% for message in messages %}
                      {{ message }}<br>
                  {% endfor %}
              </div>
              {% endif %}
          {% endwith %}
          {% for news in news_list %}
            <h3><a href={{ news.url }}>{{ news.title }}</a></h3>
            <p>{{ news.published.strftime('%d.%m.%Y') }} | Comments: {{ news.comments_count() }}</p>
            <hr />
          {% endfor %}
        </div>
        <div class="col-4">
          <h2>
            Weather forecast
          </h2>
          {% if weather %}
            Now {{ weather.temp_C }}, feels like {{ weather.FeelsLikeC }}
          {% else %}
            Service is unavailable now
          {% endif %}
        </div>

      </div>
{% endblock %}

webapp/templates/news/single_news.html
{% extends "base.html" %}
{% block content %}     
      <div class="row">
        <div class="col-8 news-content">
            {{ news.text | safe }}
        </div>
        <div class="col-4">
          <h2>
            Other news
          </h2>

        </div>

      </div>
{% endblock %}

webapp/templates/user/login.html
{% extends "base.html" %}

{% block content%}
<div class="row">
  <div class="col-4">
    {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="alert alert-warning" role="alert">
            {% for message in messages %}
                {{ message }}<br>
            {% endfor %}
        </div>
        {% endif %}
    {% endwith %}
    <form action="{{ url_for('user.process_login') }}" method="POST">
      {{ form.hidden_tag() }}
      <div class="form-group">
        {{ form.username.label }}
        {{ form.username() }}
      </div>
      <div class="form-group">
        {{ form.password.label }}
        {{ form.password() }}
      </div>
      <div class="form-group form-check">
        {{ form.remember_me() }}
        {{ form.remember_me.label(class_='form-check-label') }}
      </div>
        {{ form.submit() }}
    </form>
  </div>


</div>
 {% endblock %}

webapp/templates/user/registration.html
{% extends "base.html" %}

{% block content%}
    {% with messages = get_flashed_messages() %}
        {% if messages %}     
          {% for message in messages %}
            <div class="alert alert-danger" role="alert">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
    {% endwith %}
    <form action="{{ url_for('user.process_reg') }}" method="POST">
      {{ form.hidden_tag() }}
      <div class="form-group">
        {{ form.username.label }}
        {{ form.username() }}
      </div>
      <div class="form-group">
        {{ form.email.label }}
        {{ form.email() }}
      </div>
      <div class="form-group">
        {{ form.password.label }}
        {{ form.password() }}
      </div>
      <div class="form-group">
        {{ form.password2.label }}
        {{ form.password2() }}
      </div>
      {{ form.submit() }}
    </form>
  </div>


</div>
 {% endblock %}